export { default as Home } from './Home'
export { default as Proposition } from './Proposition'
export { default as SignUp } from './SignUp'
export { default as LandingPage } from './LandingPage'
export { default as CreateProposition } from './CreateProposition'
